### PR TITLE
chore: adding generated files in .gitignore

### PR DESCRIPTION
**Pull request by Luccasoli**
https://github.com/expo/expo/blob/master/packages/expo-yarn-workspaces/README.md#define-the-entry-module-in-the-main-field-of-each-apps-packagejson

if in any moment you need some specific configuration in your AppEntry, just put it in root of your expo project and change the "main" field in your package.json

### CODE REVIEW

**Review by gsevla — CHANGES_REQUESTED** [review]
nice!
could you just add a blank line at the end of each file?

**Comment by Luccasoli** [comment]
@gsevla deixa de baitolagem de falar ingles e olha o zap

**Review by Luccasoli — COMMENTED** [review]
done!

**Comment by Luccasoli** [comment]
> nice! could you just add a blank line at the end of each file?

done!

**Review by gsevla — APPROVED** [review]

**Pull request merged**
